### ISSUE TITLE
Can this be use to publish rails app in WSL ?

### ISSUE THREAD

**Issue by abigoroth** [peterkeen/fly-proxy#1]
You wrote that this is for cache, can it use for rails app ?

**Comment by peterkeen** [comment]
Sure. If you want to use this you'd delete everything (except the `hostnames` line) in the backends block

https://github.com/peterkeen/fly-proxy/blob/main/proxy.conf#L27-L39

and everything except the `hostnames` and `default` lines in this block:

https://github.com/peterkeen/fly-proxy/blob/main/proxy.conf#L48-L70

Then add your backend to the backends block (the first link), add a cert for that domain to your fly app, and point DNS at it. 

If you're going to use the tailscale part you'd also need to generate an OAuth key and set the `TS_OAUTH_CLIENT_SECRET` secret on your fly app. If you don't want to use the tailscale part then just delete `00-start-tailscale.sh`.

**Comment by abigoroth** [comment]
I didn't understand the steps.

I need deploy this docker app to fly.io ?
